### ISSUE TITLE
Add description field to the event (model)

### ISSUE THREAD

**Issue by EdgarDorausch** [WhatsOnToday/whatsontoday-web#54]
Preferably as formatted string (html for example, so are able to create paragraphs, bold text, etc...)

**Comment by Hoff97** [comment]
Wie genau soll die Formatierung im Backend denn unterstützt werden? Ich wäre eher für sowas wie Markdown, was dann Clientseitig gerendert wird. Da muss man auch nicht wegen XSS aufpassen...
